# Generated by Django 3.0.6 on 2020-05-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatTheCowsay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_does_the_cowsay', models.CharField(max_length=142)),
            ],
        ),
    ]
